DROP TABLE IF EXISTS Records;
DROP TABLE IF EXISTS RecordFiles;

CREATE TABLE IF NOT EXISTS Records (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RecordName NVARCHAR(255) NOT NULL,
    OriginalName NVARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS RecordFiles (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RecordID INT NOT NULL,
    Version VARCHAR(10) NOT NULL,
    Path NVARCHAR(512) NOT NULL,
    FOREIGN KEY (RecordID) REFERENCES Records(ID)
);